spring:
  application:
    name: produtos
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_redis
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  data:
    redis:
      host: localhost
      port: 6379

